### ISSUE TITLE
Export env variables to file

### ISSUE THREAD

**Issue by brunocascio** [say8425/aws-secrets-manager-actions#19]
Hi @say8425 ,

I'm using SSM to save a lot of env variables so I'm looking for a way to pass them at once.

Example:

```yaml
- name: Make environment variables from AWS SecretManager global available
  uses: say8425/aws-secrets-manager-actions@v0.10.0
  with:
     AWS_ACCESS_KEY_ID: ${{ secrets.staging_AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.staging_AWS_SECRET_ACCESS_KEY }}
     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
     SECRET_NAME: ${{ secrets.staging_SECRET_NAME }}

- name: Build package
  run: |
      env > .env
      docker-compose -f docker-compose.deploy.yml run \
        --rm --no-deps -u root \
        -v ${GITHUB_WORKSPACE}/build:/home/node/app/build \
        frontend \
        npm run build
```

As you see, I pass them via `env > .env` but it contains a lot of system envs like `PATH`, `HOME`, etc

A possible solution might be export SSM env variables to `$GITHUB_WORKSPACE/<ssm-var-name>` file.

With that implemented I would do this:

```yaml
- name: Make environment variables from AWS SecretManager global available
  uses: say8425/aws-secrets-manager-actions@v0.10.0
  with:
     AWS_ACCESS_KEY_ID: ${{ secrets.staging_AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.staging_AWS_SECRET_ACCESS_KEY }}
     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
     SECRET_NAME: ${{ secrets.staging_SECRET_NAME }}
     OUTPUT_PATH: ${{ github.workspace }}/.env

- name: Build package
  run: |
      # .env is present here
      docker-compose -f docker-compose.deploy.yml run \
        --rm --no-deps -u root \
        -v ${GITHUB_WORKSPACE}/build:/home/node/app/build \
        frontend \
        npm run build
```

With the above configuration, I only pass SSM values instead of the whole system vars
