### ISSUE TITLE
add test for gh workflow

### ISSUE THREAD

**Issue by say8425** [say8425/aws-secrets-manager-actions#49]
* https://github.com/marketplace/actions/github-action-test-automation
* I'm not sure but it will be worked??
```yml
jobs:  
  test:  
    runs-on: ubuntu-latest  
    name: test-action  
    steps:  
     - name: Store ENV from AWS SecretManager
       uses: say8425/aws-secrets-manager-actions@v1
       with:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
         SECRET_NAME: ${{ secrets.SECRET_NAME }}
     - name: Should have SCIENTIFIC_NAME
       uses: therussiankid92/gat
       with:  
         assertion: should.equal  
         expected: Pygoscelis adeliae
         actual: ${{ env.SCIENTIFIC_NAME }}  

```
* add test tag
